# Generated by Django 3.2.9 on 2021-12-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_date_joined_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='can_document',
            field=models.FileField(blank=True, max_length=254, upload_to=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner_id_document',
            field=models.FileField(blank=True, max_length=254, upload_to=None),
        ),
    ]
